### ISSUE TITLE
Cash not showing up in custom user profile data

### ISSUE THREAD

**Issue by fmartingr** [psychobunny/nodebb-plugin-cash#6]
Browser: `GET /api/cash`
`{"currency":"Rupee","points":"5336"}`

But in the lavender theme any custom info is shown. I'm not sure if this is a NodeBB bug, a Lavender bug or a cash bug! I've followed the code a little and everything seems fine. Maybe fixed in master but not in NPM?

**Comment by zetas** [comment]
I was seeing it in 0.6.x but I recently upgraded to 0.7 and i don't see it anymore anywhere using the Persona theme. I do get a message that I got "gold" (even though I changed the name of it) on every post. 

I guess I'll have to disable it for now until a newer version is released.

**Comment by rbeer** [comment]
Hey guys!
I just PR'ed my working changes:
NodeBB/nodebb-theme-persona#94
#8 

Fingers crossed. :see_no_evil:
